### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by tadeuasarro**
Microverse Third Project | This project consists of a clone an old version of Apple's homepage. HTML5, CSS3 a bit responsive.
 .

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- This project can not be considered valid for review until it contains a meaningful PR mesasge.  Please add meaningful title and short summary of the features added in the Pull Requests before continuing! (only mentioning that the proejct "is almos finished" and mentioning only *one* single feature is insufficient)

image


### Submit these changes and request a new code review! 😄 👍 
### Questions of comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by Alexoid1** [comment]
#Apple Homepage using @media for responsiveness and grid and flexbox for elements deploy

This project is a clone version of Apple Homepage that was recreated with pure css and html and fontawesome for the icons and Web Developer google chrome Extension to get the original images .

**Comment by andresporras3423** [comment]
### **Pull Request Under Review By Oscar Russi (TSE)**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello @tadeuasarro @Alexoid1** 
Good job with your first submission for this project :muscle:  
your page pass most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [ ] The 4 images at the bottom of the page should be links
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. By now the validator shows some errors in your code:



#### OPTIONAL
 - [ ] it's recommended to use the main tag for the dominant content of the body of the document

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras
(for any question you can contact me in slack as @oscarporras02)

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Status: Approved ✔

## What an impressive project team 👏🙌👌!

### Thank you for implementing all the changes requested by the previous reviewers.

You can move ahead and merge it but it would be really beneficial for you down the road if you can make these [OPTIONAL] changes.

### [OPTIONAL]

- Consider putting the search icon in the `navbar-ul-input` class to match the original.

  Right now 👇

  Annotation 2020-06-16 084807

  Original 👇

  Annotation 2020-06-16 084826

- There is extra space on either side of the `article`, `aside`, and `footer` elements. Consider removing them.
   
  Annotation 2020-06-16 085154

That's it, team. Consider adding the search icon and removing the extra space.

### Onto the next project 🚀.

Happy coding 👨‍💻

**Pull request merged**
